### ISSUE TITLE
Mvp4gMultiPresenterWithHistorieExample Maven build error

### ISSUE THREAD

**Issue by carlolf** [mvp4g/mvp4g-examples#7]
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:compile (default) on project Mvp4gMultiPresenterWithHistorieExample: GWT Module dde.gishmo.mvp4g.example.multipresenterwithhistorie.client.Mvp4gMultiPresenterWithHistorieExample not found in project sources or resources.`

There is a type in pom.xml at the module definition ("dde." instead "de"). But correcting this doesn't really fix the problem.

**Comment by carlolf** [comment]
the module file is not in the right directory; it should be placed into in a further "client" directory.

Doing this, another build error appears:
`[ERROR] Hint: Check the inheritance chain from your module; it may not be inheriting a required module or a module may not be adding its source path entries properly`

**Comment by mvp4g** [comment]
Updated pom, please try again
