### ISSUE TITLE
Mvp4gMultiPresenterWithHistorieExample: PANIC!!!

### ISSUE THREAD

**Issue by carlolf** [mvp4g/mvp4g-examples#8]
This example now builds with no problems. Deploying it to my local Tomcat, calling the entry Page with Chrome shows the window and the dialog "Personen" with an empty table (ok), but an error dialog appears immediately : "PANIC!!!!". Clicking it away, I tried to insert a new person with "Neue Person". The dialog tab appears, and I put in same data. Then, pressing the "Save" button, the "PANIC!!!" error message dialog appears again.

This is fom Chromes Console view:

`Failed to load resource: the server responded with a status of 500 ()
http://localhost:8080/Mvp4gMultiPresenterWithHistorieExample-1.0-SNAPSHOT/mvp4gmultipresenterwithhistorieexample/history Failed to load resource: the server responded with a status of 500 ()
http://localhost:8080/Mvp4gMultiPresenterWithHistorieExample-1.0-SNAPSHOT/mvp4gmultipresenterwithhistorieexample/person Failed to load resource: the server responded with a status of 500 ()
mvp4gmultipresenterwithhistorieexample-0.js:2805 POST http://localhost:8080/Mvp4gMultiPresenterWithHistorieExample-1.0-SNAPSHOT/mvp4gmultipresenterwithhistorieexample/person 500 ()
Tl @ mvp4gmultipresenterwithhistorieexample-0.js:2805
EJ @ mvp4gmultipresenterwithhistorieexample-0.js:2781
JJ @ mvp4gmultipresenterwithhistorieexample-0.js:2213
kIb @ mvp4gmultipresenterwithhistorieexample-0.js:2562
vJb @ mvp4gmultipresenterwithhistorieexample-0.js:2064
MJb @ mvp4gmultipresenterwithhistorieexample-0.js:2980
ayb @ mvp4gmultipresenterwithhistorieexample-0.js:2979
rl @ mvp4gmultipresenterwithhistorieexample-0.js:2807
jl @ mvp4gmultipresenterwithhistorieexample-0.js:2574
TP @ mvp4gmultipresenterwithhistorieexample-0.js:1045
nQ @ mvp4gmultipresenterwithhistorieexample-0.js:2306
xQ @ mvp4gmultipresenterwithhistorieexample-0.js:2975
emb @ mvp4gmultipresenterwithhistorieexample-0.js:2400
hqb @ mvp4gmultipresenterwithhistorieexample-0.js:2979
vG @ mvp4gmultipresenterwithhistorieexample-0.js:2018
KH @ mvp4gmultipresenterwithhistorieexample-0.js:1951
Hc @ mvp4gmultipresenterwithhistorieexample-0.js:1261
Kc @ mvp4gmultipresenterwithhistorieexample-0.js:1766
(anonymous) @ mvp4gmultipresenterwithhistorieexample-0.js:1840
mvp4gmultipresenterwithhistorieexample-0.js:2805 XHR finished loading: POST "http://localhost:8080/Mvp4gMultiPresenterWithHistorieExample-1.0-SNAPSHOT/mvp4gmultipresenterwithhistorieexample/person".`

**Comment by carlolf** [comment]
Still too much PANICs!!!!!

I loaded the example into my Eclipse, searched "PANIC!!!!" and replaced the alerts with some additional hints to see where the panic window was invoked. This is what happens:

On start:
- ContentPresenter.doUpdatePersonGrid
- PersistentHandel.save

After trying to save a new person record:
- PersonPresenter.doSave, personService.insert
Cancelling the new Person dialog:
- ContentPresenter.doUpdatePersonGrid

**Comment by carlolf** [comment]
I think the reason of these PANICS is, that the services are not running, they are not reachable. It's a somewhat curious thing. The Tomcat server starts, it starts the Webapp with no errors. But it should have errors - because there is no lib directory in the deployed webapp. Therefore there is not gwt-servlet.jar etc.

I do not know how to configure the Maven POM so that the build of the war also creates the lib folder and copies the needed runtime jars.

**Comment by mvp4g** [comment]
I have updated the pom. gwt-servlet.jar will be deployed now. Please try again.

**Comment by carlolf** [comment]
Confirm: after pull, rebuild, redeploy, the sample now runs fine. Thank you.
